import numpy as np 
sensor1=np.array([[25,28,30],[27,29,31]])
sensor2=np.array([[26,27,29],[28,30,32]])
print("Sensor 1 Shape:",sensor1.shape," Dimension:",sensor1.ndim," Size:",sensor1.size)
print("Sensor 2 Shape:",sensor2.shape," Dimension:",sensor2.ndim," Size:",sensor2.size)
print("------------------------------------------------")
print("Sensor 1 Element(2,3):",sensor1[1,2])
print("Sensor 2:",sensor2[0,:])
print("Last two Columns of Both Sensors:",sensor1[:,1:],"\n",sensor2[:,1:])
print("------------------------------------------------")
print("Adding Both Sensors:",np.add(sensor1,sensor2))
print("Subtracting both Sensors:",np.subtract(sensor2,sensor1))
print("------------------------------------------------")
print("Where Sensor 1 Greater are than Sensor2:",sensor1>sensor2)
print("Values from Sensor 1 less than 30:",sensor1<30)
print("------------------------------------------------")
print("Mean of Both Combined:",np.mean([sensor1,sensor2]))
print("Max Temp Element:",np.max([sensor1,sensor2]))
print("Min Temp Element:",np.min([sensor1,sensor2]))
print("Standard Deviation:",np.std([sensor1,sensor2]))
print("------------------------------------------------")
print("Square of both Sensors:\n",np.square([sensor1,sensor2]))
print("------------------------------------------------")
print("Flatten both Sensors:",sensor1.flatten(),sensor2.flatten())
final_data=np.array([sensor1,sensor2]).flatten()
print("Flatten both Sensors:",final_data)
print("------------------------------------------------")
print("Reshape into(3,4):",final_data.reshape(3,4))
print("------------------------------------------------")
print("Final data only values greater than 28 and less than 32:",final_data[(final_data>28) & (final_data<32)])
#huda ki gaadi leke aaye